name: CI

on: push

jobs:
  push-to-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: pnpm/action-setup@v4
        with:
          run_install: true
      - run: pnpm run build

      - name: Push file
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY}}
        with:
          source-directory: dist
          target-directory: aria2-anime
          destination-github-username: niyoh120
          destination-repository-name: userscripts
          user-email: zhrh120@gmail.com
          target-branch: master
